# Generated by Django 2.1.7 on 2019-07-08 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a group name', max_length=20)),
                ('description', models.CharField(help_text='Enter description of group', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a user name', max_length=20)),
                ('created', models.DateField(default=datetime.date.today)),
                ('group', models.CharField(help_text='Select a group', max_length=20)),
            ],
        ),
    ]
