# Generated by Django 2.1.7 on 2019-07-10 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_auto_20190709_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 13, 16, 57, 136218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.IntegerField(choices=[(1, 'Yellows'), (2, 'Red'), (3, 'Blue')]),
        ),
    ]
