# Generated by Django 2.1.7 on 2019-07-10 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0005_auto_20190710_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 16, 59, 12, 195565)),
        ),
    ]
