# Generated by Django 2.1.7 on 2019-07-10 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0006_auto_20190710_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 19, 16, 18, 900063)),
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.IntegerField(choices=[('Yellows', 1), ('Red', 2), ('Blue', 3)]),
        ),
    ]
